version: '3.0'

services:
    app:
        container_name: php_lesson_2_app
        build:
            context: .
            dockerfile: .docker/app/Dockerfile
        working_dir: /app
        volumes:
            - ./app:/app
    webserver:
        container_name: php_lesson_2_webserver
        build:
            context: .
            dockerfile: .docker/webserver/Dockerfile
        working_dir: /app
        volumes:
            - ./app:/app
        ports:
            - '8080:80'